# Generated by Django 5.1.1 on 2024-10-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
